# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b956d83f4d889cd8fd8931e9dc461797cceb02001565e64fd789b5006ee8619e36bb58221fa54318e0a812f21a5d08b373a4c28fed170bb4609854f31f610e8

test:
  secret_key_base: 7f3c3344bfc1a83ea276454de5fbe6c4b110938b4ba938fc6ebdacef292e118ebf1c3cfc879a8dda3098c35e590c6d74c0499eee601653059f1864d44121d530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
